# fmt: off
[
    {
      "name": "neighbors",
      "getval": '''^(?P<address>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+(?P<interface>\S+)\s+(?P<peer_state>\S+)\s+(?P<neighbor_id>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+(?P<priority>\d+)\s+(?P<dead_time>\S+)''',
      "result": {
        "neighbors": [
        {
          "neighbor_id": "{{ neighbor_id }}",
          "priority": "{{ priority }}",
          "peer_state": "{{ peer_state }}",
          "dead_time": "{{ dead_time }}",
          "address": "{{ address }}",
          "interface": "{{ interface }}",
        }
        ]
      }
    }
]
 # fmt: on