---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.persist
  vars:
    resources:
      - 'ospfv2'
      - 'ospfv3'
      - 'ospf_interfaces'
    ignore_empty: "{{ persist_empty | default(true) }}"
